version: "3"
services:
    docker-bts-cache:
        image: redis:latest
        deploy:
        replicas: 1
        restart: always
    docker-bts-api:
        image: bodastage/bts-api
        ports:
          - "8080:80"
        restart: always
        networks:
          - host
    docker-bts-web:
        image: nginx:alpine
        ports:
          - "80:80"
        volumes:
            - $(pwd)/www:/usr/share/nginx/html
        networks:
          - host
    docker-bts-mediation:
        image: bodastage/bts-mediation
        restart: always
        ports:
          - "3141:8080"
        environment:
            POSTGRES_HOST: $(docker-machine ip)
        volumes:
           - $(pwd)/dags:/usr/local/airflow/dags
           - $(pwd)/logs:/usr/local/airflow/logs
           - $(pwd)/mediation:/mediation
        networks:
          - host
    docker-bts-database:
        image: postgres:9.6
        restart: always
        environment:
          POSTGRES_PASSWORD: password
        volumes:
            - $(pwd)/db/setup:/docker-entrypoint-initdb.d
            - $(pwd)/db/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
          - bts-net