version: "3"
services:
    bts-database:
        image: postgres:10.1
        restart: always
        environment:
          - POSTGRES_PASSWORD=password
        volumes:
            - ./db/setup:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        network_mode: "bridge"
        container_name: "bts-database"
    bts-msgbroker:
        image: rabbitmq:3.7.4-management
        restart: always
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
            - "15674:15674"
            - "61613:61613"
            - "15670:15670"
        network_mode: "bridge"
        container_name: "bts-msgbroker"
    bts-api:
        image: bodastage/bts-ce-api
        ports:
          - 8181:8181
        restart: always
        volumes:
          - ./bts-ce-api:/app
        depends_on: 
            - bts-database
            - bts-msgbroker
        links:
          - "bts-database:database"
        network_mode: "bridge"
        container_name: "bts-api"
    bts-web:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./web:/usr/share/nginx/html
        network_mode: "bridge"
        container_name: "bts-web"
        depends_on: 
            - bts-msgbroker
    bts-mediation:
        image: bodastage/bts-ce-mediation
        restart: always
        ports:
          - "8080:8080"
        environment:
            - POSTGRES_HOST=database
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres+psycopg2://airflow:airflow@database:5432/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
           - ./mediation/dags:/usr/local/airflow/dags
           - ./mediation:/mediation
        command: webserver
        depends_on: 
           - bts-database
           - bts-msgbroker
        network_mode: "bridge"
        container_name: "bts-mediation"
        links:
            - "bts-database:database"
    bts-cache:
        image: redis:latest
        ports:
          - "6380:6380"
        network_mode: "bridge"
    bts-ce-database:
        image: bodastage/bts-ce-database
        restart: always
        environment:
          - POSTGRES_PASSWORD=password
        volumes:
            - ./db/setup:/docker-entrypoint-initdb.d
            - ./bts-ce-database:/migrations
        ports:
            - "5432:5432"
        network_mode: "bridge"
        container_name: "bts-ce-database"